---
apiVersion: v1
kind: Secret
metadata:
  name: backup-credentials
type: Opaque
stringData:
  username: myaccesskey
  password: mysecretkey
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-repo
type: Opaque
stringData:
  password: myreposecret
---
apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: k8up-backup
spec:
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  backend:
    repoPasswordSecretRef:
      name: backup-repo
      key: password
    s3:
      endpoint: http://minio.minio.svc.cluster.local:9000
      bucket: backup
      accessKeyIDSecretRef:
        name: backup-credentials
        key: username
      secretAccessKeySecretRef:
        name: backup-credentials
        key: password
